# Generated by Django 4.2.1 on 2023-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
