# Generated by Django 4.2.1 on 2023-06-08 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_leaderboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaderboard',
            new_name='Board',
        ),
    ]
