# Generated by Django 4.2.1 on 2023-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_flag_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='score',
            field=models.IntegerField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=10),
        ),
    ]
