# Generated by Django 4.2.1 on 2023-06-19 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_flag_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
