# Generated by Django 4.2.1 on 2023-06-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_board_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='f3',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='f4',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='f5',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='h3',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='h4',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='h5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hint_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hint_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hint_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hint_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hint_5',
        ),
    ]
