# Generated by Django 4.2.3 on 2023-09-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_flag_f2_remove_flag_f3_remove_flag_f4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
