# Generated by Django 4.2.3 on 2023-09-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(blank=True, max_length=200)),
                ('h1', models.CharField(blank=True, max_length=200)),
                ('f1', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(blank=True, choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=10)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
