# Generated by Django 4.2.3 on 2023-09-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_flags_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='hint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.flags'),
        ),
    ]
