# Generated by Django 4.2.3 on 2023-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_complete_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags',
            name='q1',
            field=models.IntegerField(blank=True, default=1, max_length=200),
        ),
    ]
