# Generated by Django 4.2.3 on 2023-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flags',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
