# Generated by Django 4.2.2 on 2023-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="h1",
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
