# Generated by Django 4.2.2 on 2023-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0024_alter_flag_h1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="h1",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
